name: Github Actions in Windows

on: push

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        python-version: '3.12'
        activate-environment: pyprecag_up
    - run: |
        conda install geopandas rasterio -c conda_forge -y
        conda install fiona six chardet unidecode scipy pint -c conda_forge -y
        conda install libsqlite sqlite -c conda_forge -y
        conda install gdal -c conda_forge -y
        conda install flake8 -c conda-forge -y
        pip install .
    
