name: Github Actions in Windows

on: push

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        python-version: '3.12'
        activate-environment: pyprecag_up
    - run: |
        conda init powershell
        conda install geopandas rasterio -c conda-forge -y
        conda install fiona six chardet unidecode scipy pint -c conda-forge -y
        conda install libsqlite sqlite -c conda-forge -y
        conda install gdal -c conda-forge -y
        conda install flake8 -c conda-forge -y
        pip install .
        conda list
        python -m unittest pyprecag/tests/test_bandops.py
    - run: |
        # stop the build if there are Python syntax errors or undefined names
        ##flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        ##flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - run: |
        # Unit Tests
        conda list
        conda activate pyprecag_up
        python -m unittest pyprecag/tests/test_bandops.py
    
