name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create Dummy File
     run: |
         echo "Dummy" > test42.md
    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'test42.md'
        destination_repo: 'CSIRO-Precision-Agriculture/pyprecag_docs'
        destination_folder: 'test-dir'
        destination_branch: 'mnb_pages'
        user_email: 'action@github.com'
        user_name: 'GitHub Action'
        commit_message: 'Simply adding a test file'
